coverage:
  status:
    project:
      default:
        # basic
        target: 85%
        threshold: 20%
    patch:
      default:
        # basic
        target: 85%
        threshold: 20%
    ignore:
      - build/_deps/
